from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import database_models
from database import session, engine
from auth_api import router as auth_router
from pythonlearn import router as pythonlearn_router
from sqlalchemy import text

app = FastAPI()

# Allow browser clients from common local frontend ports.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:4200",
        "http://127.0.0.1:4200",
        "http://localhost:5500",
        "http://127.0.0.1:5500",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

database_models.Base.metadata.create_all(bind=engine)


def ensure_auth_table_columns() -> None:
    # Keep DB schema aligned with ORM fields when table already exists.
    with engine.begin() as connection:
        connection.execute(text('ALTER TABLE auth ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY'))
        connection.execute(text('ALTER TABLE auth ADD COLUMN IF NOT EXISTS "fullName" VARCHAR'))
        connection.execute(text('ALTER TABLE auth ADD COLUMN IF NOT EXISTS "mobileNumber" VARCHAR'))
        connection.execute(text('ALTER TABLE auth ADD COLUMN IF NOT EXISTS "username" VARCHAR'))
        connection.execute(text('ALTER TABLE auth ADD COLUMN IF NOT EXISTS "password" VARCHAR'))


ensure_auth_table_columns()

@app.get('/')
def greet():
    return "welconme to the krishna world"


app.include_router(auth_router, prefix="/auth", tags=["Auth"])
app.include_router(pythonlearn_router, prefix="/pythonlearn", tags=["Pythonlearn"])
